obj-m += lux-core.o
obj-m += lux-gpio-chip.o
obj-m += lux-cdev.o
# obj-m += lux-regmap.o
obj-m += lux-led.o
obj-m += lux-led-mc.o
obj-m += lux-irq.o
obj-m += lux-timer.o
obj-m += kthread-time.o

ccflags-y := -I ${src}/include
lux-timer-y := lux-timer-core.o lux-timer-fops.o
