obj-m += lux-core.o
obj-m += lux-gpio-chip.o
obj-m += lux-cdev.o
# obj-m += lux-regmap.o
obj-m += lux-led.o
obj-m += lux-led-mc.o
obj-m += lux-irq.o
obj-m += lux-timer.o

ccflags-y := -I ${src}/include
#lux-core-y := lux-core.o
#lux-gpio-manual-y := lux-gpio-manual.o
